// 紧凑数据表减少重复字段，导出时再生成小程序统一使用的词条结构。
const entries = [
  ['adventure', '/ədˈventʃər/', 'n. 冒险；奇遇', 'Life is a great adventure.', '生活是一场伟大的冒险。', 1],
  ['ability', '/əˈbɪləti/', 'n. 能力；才能', 'She has the ability to solve the problem.', '她有解决这个问题的能力。', 1],
  ['achieve', '/əˈtʃiːv/', 'v. 实现；取得', 'Hard work helps us achieve our goals.', '努力帮助我们实现目标。', 1],
  ['advantage', '/ədˈvæntɪdʒ/', 'n. 优势；有利条件', 'Experience gives her an advantage.', '经验给了她优势。', 1],
  ['affect', '/əˈfekt/', 'v. 影响', 'Weather can affect our plans.', '天气会影响我们的计划。', 1],
  ['allow', '/əˈlaʊ/', 'v. 允许；准许', 'The rules allow one more attempt.', '规则允许再尝试一次。', 1],
  ['ancient', '/ˈeɪnʃənt/', 'adj. 古代的；古老的', 'They visited an ancient city.', '他们参观了一座古城。', 1],
  ['approach', '/əˈproʊtʃ/', 'n. 方法；v. 接近', 'We need a new approach to learning.', '我们需要一种新的学习方法。', 2],
  ['argue', '/ˈɑːrɡjuː/', 'v. 争论；主张', 'They argue about the best solution.', '他们争论哪种方案最好。', 1],
  ['arrange', '/əˈreɪndʒ/', 'v. 安排；整理', 'Please arrange the books by topic.', '请按主题整理这些书。', 1],
  ['article', '/ˈɑːrtɪkəl/', 'n. 文章；物品', 'I read an article about technology.', '我读了一篇关于科技的文章。', 1],
  ['attend', '/əˈtend/', 'v. 出席；参加', 'Many students attend the lecture.', '许多学生参加了讲座。', 1],
  ['average', '/ˈævərɪdʒ/', 'n. 平均数；adj. 平均的', 'The average score is eighty.', '平均分是八十分。', 1],
  ['avoid', '/əˈvɔɪd/', 'v. 避免', 'Try to avoid the same mistake.', '尽量避免犯同样的错误。', 1],
  ['balance', '/ˈbæləns/', 'n. 平衡；v. 使平衡', 'Work and rest should stay in balance.', '工作和休息应当保持平衡。', 1],
  ['behavior', '/bɪˈheɪvjər/', 'n. 行为；举止', 'Good behavior builds trust.', '良好的行为能够建立信任。', 2],
  ['benefit', '/ˈbenɪfɪt/', 'n. 好处；v. 受益', 'Regular reading has many benefits.', '经常阅读有很多好处。', 1],
  ['challenge', '/ˈtʃælɪndʒ/', 'n. 挑战；v. 挑战', 'Learning a language is a challenge.', '学习一门语言是一项挑战。', 1],
  ['change', '/tʃeɪndʒ/', 'n. 变化；v. 改变', 'Small habits can change your life.', '小习惯能够改变你的生活。', 1],
  ['choice', '/tʃɔɪs/', 'n. 选择', 'You have a choice between two modes.', '你可以在两种模式之间选择。', 1],
  ['communicate', '/kəˈmjuːnɪkeɪt/', 'v. 沟通；传达', 'We communicate through language.', '我们通过语言沟通。', 2],
  ['compare', '/kəmˈper/', 'v. 比较；对照', 'Compare the two answers carefully.', '仔细比较这两个答案。', 1],
  ['complete', '/kəmˈpliːt/', 'v. 完成；adj. 完整的', 'Complete ten words today.', '今天完成十个单词。', 1],
  ['concern', '/kənˈsɜːrn/', 'n. 担忧；v. 涉及', 'Safety is our main concern.', '安全是我们最关心的问题。', 2],
  ['consider', '/kənˈsɪdər/', 'v. 考虑；认为', 'Please consider every option.', '请考虑每个选项。', 1],
  ['continue', '/kənˈtɪnjuː/', 'v. 继续', 'She continued her daily practice.', '她继续每天练习。', 1],
  ['create', '/kriˈeɪt/', 'v. 创造；创建', 'We can create a better method.', '我们可以创造一种更好的方法。', 1],
  ['culture', '/ˈkʌltʃər/', 'n. 文化', 'Language is part of culture.', '语言是文化的一部分。', 1],
  ['decide', '/dɪˈsaɪd/', 'v. 决定', 'They decided to study together.', '他们决定一起学习。', 1],
  ['describe', '/dɪˈskraɪb/', 'v. 描述；形容', 'Can you describe the picture?', '你能描述这幅图片吗？', 1],
  ['develop', '/dɪˈveləp/', 'v. 发展；培养', 'Reading develops critical thinking.', '阅读能够培养批判性思维。', 1],
  ['difference', '/ˈdɪfrəns/', 'n. 差异；不同', 'Practice makes a real difference.', '练习会带来真正的改变。', 1],
  ['difficult', '/ˈdɪfɪkəlt/', 'adj. 困难的', 'The last question was difficult.', '最后一道题很难。', 1],
  ['discover', '/dɪˈskʌvər/', 'v. 发现', 'We discover new words every day.', '我们每天发现新单词。', 1],
  ['education', '/ˌedʒuˈkeɪʃən/', 'n. 教育', 'Education creates opportunities.', '教育创造机会。', 1],
  ['effect', '/ɪˈfekt/', 'n. 影响；效果', 'The new method has a good effect.', '新方法产生了良好效果。', 2],
  ['effort', '/ˈefərt/', 'n. 努力', 'Your effort will bring progress.', '你的努力会带来进步。', 1],
  ['encourage', '/ɪnˈkɜːrɪdʒ/', 'v. 鼓励', 'Teachers encourage us to ask questions.', '老师鼓励我们提问。', 1],
  ['environment', '/ɪnˈvaɪrənmənt/', 'n. 环境', 'A quiet environment helps learning.', '安静的环境有助于学习。', 1],
  ['experience', '/ɪkˈspɪriəns/', 'n. 经验；经历', 'Practice gives you experience.', '练习能够给你经验。', 1],
  ['explain', '/ɪkˈspleɪn/', 'v. 解释；说明', 'Please explain your answer.', '请解释你的答案。', 1],
  ['familiar', '/fəˈmɪliər/', 'adj. 熟悉的', 'This word looks familiar.', '这个单词看起来很熟悉。', 1],
  ['feature', '/ˈfiːtʃər/', 'n. 特征；功能', 'The app has a review feature.', '这个应用有复习功能。', 2],
  ['final', '/ˈfaɪnəl/', 'adj. 最后的；最终的', 'Check your final answer.', '检查你的最终答案。', 1],
  ['focus', '/ˈfoʊkəs/', 'v. 集中；n. 焦点', 'Focus on one task at a time.', '一次专注于一项任务。', 1],
  ['foreign', '/ˈfɔːrən/', 'adj. 外国的；陌生的', 'She is learning a foreign language.', '她正在学习一门外语。', 1],
  ['improve', '/ɪmˈpruːv/', 'v. 改进；提高', 'Daily review can improve memory.', '每日复习可以提高记忆力。', 1],
  ['include', '/ɪnˈkluːd/', 'v. 包含；包括', 'The lesson includes ten words.', '这节课包含十个单词。', 1],
  ['increase', '/ɪnˈkriːs/', 'v. 增加；提高', 'Reading can increase your vocabulary.', '阅读可以增加你的词汇量。', 1],
  ['influence', '/ˈɪnfluəns/', 'n. 影响；v. 影响', 'Friends can influence our choices.', '朋友会影响我们的选择。', 2],
  ['information', '/ˌɪnfərˈmeɪʃən/', 'n. 信息；资料', 'The page provides useful information.', '这个页面提供有用的信息。', 1],
  ['instead', '/ɪnˈsted/', 'adv. 代替；反而', 'Try again instead of giving up.', '再试一次，而不是放弃。', 1],
  ['interest', '/ˈɪntrəst/', 'n. 兴趣；v. 使感兴趣', 'Stories can build interest in reading.', '故事能够培养阅读兴趣。', 1],
  ['knowledge', '/ˈnɑːlɪdʒ/', 'n. 知识', 'Reading expands our knowledge.', '阅读拓展我们的知识。', 1],
  ['language', '/ˈlæŋɡwɪdʒ/', 'n. 语言', 'English is an international language.', '英语是一门国际语言。', 1],
  ['manage', '/ˈmænɪdʒ/', 'v. 管理；设法做到', 'She manages her time well.', '她很好地管理自己的时间。', 1],
  ['measure', '/ˈmeʒər/', 'v. 测量；n. 措施', 'Tests measure learning progress.', '测试衡量学习进度。', 2],
  ['method', '/ˈmeθəd/', 'n. 方法', 'This method is simple and useful.', '这种方法简单而有用。', 1],
  ['necessary', '/ˈnesəseri/', 'adj. 必要的', 'Regular practice is necessary.', '经常练习是必要的。', 1],
  ['notice', '/ˈnoʊtɪs/', 'v. 注意到；n. 通知', 'Did you notice the difference?', '你注意到这个差异了吗？', 1],
  ['opportunity', '/ˌɑːpərˈtuːnəti/', 'n. 机会', 'This is a good opportunity to learn.', '这是一个学习的好机会。', 1],
  ['organize', '/ˈɔːrɡənaɪz/', 'v. 组织；整理', 'Organize your notes after class.', '课后整理你的笔记。', 1],
  ['particular', '/pərˈtɪkjələr/', 'adj. 特定的；特别的', 'Focus on this particular example.', '专注于这个特定例子。', 2],
  ['perform', '/pərˈfɔːrm/', 'v. 表现；执行', 'Students perform better with practice.', '学生通过练习表现得更好。', 2],
  ['possible', '/ˈpɑːsəbəl/', 'adj. 可能的', 'Choose the best possible answer.', '选择尽可能好的答案。', 1],
  ['practice', '/ˈpræktɪs/', 'n. 练习；v. 练习', 'Practice makes learning easier.', '练习让学习变得更容易。', 1],
  ['prepare', '/prɪˈper/', 'v. 准备', 'Prepare your notes before class.', '上课前准备好笔记。', 1],
  ['prevent', '/prɪˈvent/', 'v. 防止；阻止', 'Review helps prevent forgetting.', '复习有助于防止遗忘。', 1],
  ['probably', '/ˈprɑːbəbli/', 'adv. 很可能；大概', 'She will probably finish today.', '她很可能今天完成。', 1],
  ['produce', '/prəˈduːs/', 'v. 生产；产生', 'Good habits produce good results.', '好习惯产生好结果。', 2],
  ['protect', '/prəˈtekt/', 'v. 保护', 'Strong passwords protect your data.', '强密码可以保护你的数据。', 1],
  ['provide', '/prəˈvaɪd/', 'v. 提供', 'Examples provide useful context.', '例句提供有用的语境。', 1],
  ['purpose', '/ˈpɜːrpəs/', 'n. 目的；用途', 'The purpose is to remember words.', '目的是记住单词。', 1],
  ['realize', '/ˈriːəlaɪz/', 'v. 意识到；实现', 'I realize why the answer is wrong.', '我意识到答案为什么错了。', 1],
  ['receive', '/rɪˈsiːv/', 'v. 收到；接受', 'You will receive immediate feedback.', '你会收到即时反馈。', 1],
  ['reduce', '/rɪˈduːs/', 'v. 减少；降低', 'Review can reduce mistakes.', '复习可以减少错误。', 1],
  ['relationship', '/rɪˈleɪʃənʃɪp/', 'n. 关系；联系', 'Words have a close relationship with context.', '单词与语境有密切联系。', 2],
  ['remember', '/rɪˈmembər/', 'v. 记得；记住', 'Pictures help us remember words.', '图片帮助我们记住单词。', 1],
  ['require', '/rɪˈkwaɪər/', 'v. 需要；要求', 'Progress requires regular effort.', '进步需要持续努力。', 1],
  ['research', '/rɪˈsɜːrtʃ/', 'n. 研究；v. 调查', 'The team conducts language research.', '这个团队开展语言研究。', 2],
  ['result', '/rɪˈzʌlt/', 'n. 结果；后果', 'The result shows clear progress.', '结果显示出明显进步。', 1],
  ['society', '/səˈsaɪəti/', 'n. 社会', 'Language changes with society.', '语言随着社会而变化。', 2],
  ['solution', '/səˈluːʃən/', 'n. 解决办法；答案', 'We found a simple solution.', '我们找到了一个简单的解决办法。', 1],
  ['suggest', '/səˈdʒest/', 'v. 建议；表明', 'I suggest reviewing the wrong words.', '我建议复习错词。', 1],
  ['support', '/səˈpɔːrt/', 'v. 支持；n. 支持', 'Friends support each other.', '朋友互相支持。', 1],
  ['technology', '/tekˈnɑːlədʒi/', 'n. 技术；科技', 'Technology changes how we learn.', '科技改变了我们的学习方式。', 1],
  ['tradition', '/trəˈdɪʃən/', 'n. 传统', 'The festival follows an old tradition.', '这个节日遵循一项古老传统。', 2],
  ['understand', '/ˌʌndərˈstænd/', 'v. 理解；明白', 'Examples help us understand meaning.', '例句帮助我们理解含义。', 1],
  ['value', '/ˈvæljuː/', 'n. 价值；v. 重视', 'We value steady progress.', '我们重视稳定的进步。', 1],
  ['various', '/ˈveriəs/', 'adj. 各种各样的', 'Try various ways to remember it.', '尝试用各种方法记住它。', 1],
  ['volunteer', '/ˌvɑːlənˈtɪr/', 'n. 志愿者；v. 自愿', 'A volunteer helped at the event.', '一名志愿者在活动中提供了帮助。', 2],
  ['whether', '/ˈweðər/', 'conj. 是否', 'Decide whether the answer is correct.', '判断答案是否正确。', 1],
  ['accept', '/əkˈsept/', 'v. 接受；认可', 'Learn to accept useful feedback.', '学会接受有用的反馈。', 1],
  ['account', '/əˈkaʊnt/', 'n. 账户；叙述', 'Your account stores learning progress.', '你的账户保存学习进度。', 2],
  ['available', '/əˈveɪləbəl/', 'adj. 可用的；有空的', 'The lesson is available offline.', '这节课程可以离线使用。', 1],
  ['community', '/kəˈmjuːnəti/', 'n. 社区；群体', 'The community shares learning resources.', '这个社区分享学习资源。', 2],
  ['condition', '/kənˈdɪʃən/', 'n. 条件；状况', 'The device is in good condition.', '这台设备状况良好。', 2],
  ['confidence', '/ˈkɑːnfɪdəns/', 'n. 信心；自信', 'Practice builds confidence.', '练习能够建立信心。', 1],
  ['creative', '/kriˈeɪtɪv/', 'adj. 有创造力的', 'She found a creative way to study.', '她找到了一种有创意的学习方法。', 1],
  ['responsible', '/rɪˈspɑːnsəbəl/', 'adj. 负责的；有责任的', 'You are responsible for your progress.', '你要对自己的进步负责。', 2],
];

module.exports = {
  id: 'cet4-core-100',
  name: '四级核心词汇',
  description: 'WordRush MVP 内置四级核心词汇',
  words: entries.map((entry, index) => ({
    id: `cet4-${String(index + 1).padStart(3, '0')}`,
    word: entry[0],
    phonetic: entry[1],
    meaning: entry[2],
    example: entry[3],
    exampleTranslation: entry[4],
    difficulty: entry[5],
    order: index + 1,
  })),
};
